-- AlterTable
ALTER TABLE `retweet` ADD COLUMN `retweetedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `save` ADD COLUMN `savedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
